FROM maven:3-jdk-13-alpine

VOLUME /tmp

ENV JAVA_OPTS=""

RUN addgroup -S app && adduser -S -g app app && apk update && apk upgrade

# https://www.alpinelinux.org/posts/Docker-image-vulnerability-CVE-2019-5021.html
# https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5021
# make sure root login is disabled
RUN sed -i -e 's/^root::/root:!:/' /etc/shadow

WORKDIR /home/app

# COPY target/*.jar app.jar
COPY . $WORKDIR
RUN mvn clean install && \
    chown -R app:app /home/app && \
    cp -v target/*.jar app.jar
    
EXPOSE 8080

USER app

# CMD java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar
CMD ["java", "$JAVA_OPTS","-Djava.security.egd=file:/dev/./urandom -jar app.jar"]
# CMD [ "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar" ]
# ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar" ]
